name: Delete Branch Extensions

on:
  delete:

permissions:
  contents: write

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  delete-branch-ext:
    name: Delete Branch Extensions
    runs-on: ubuntu-latest
    steps:
      - name: Check branch pattern
        run: |
          if [[ ! "${{ github.ref_name }}" =~ ^[0-9]+\.[0-9]+/.+ ]]; then
            echo "Skip" && exit 0
          fi
      - name: Checkout Branch
        uses: actions/checkout@v6
        with:
          ref: "gh-pages"
      - name: Git Configuration
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Delete Branch Extensions
        run: rm -rf "./${{ github.event.ref }}"
      - name: Commit and Push
        run: |
          git add --all
          if git diff --cached --quiet; then
            echo "Nothing to delete"
            exit 0
          fi
          git commit -m "Delete branch extensions"
          git pull --rebase
          git push origin gh-pages
